Change columns display names on station and delivery properties dialog.
SiLeBAT/fcl-client pull request #672
Opened 2022-08-24 16:46 UTC by birgitlewicki

Ticket: #421

Changed station and delivery properties dialog:
vip properties and more properties now have the same organization as columns of the filter table and the highlighting options

2022-08-31 11:22 UTC, ruegenbfr requested changes

2022-08-31 11:22 UTC, ruegenbfr commented on src/app/tracing/util/constants.ts
> +        'Amount',
Please replace by `'amount',`

2022-09-01 09:21 UTC, birgitlewicki commented on src/app/tracing/services/table.service.ts
> +            { id: 'Amount', name: 'Amount' },
done!

2022-09-01 09:21 UTC, birgitlewicki commented on src/app/tracing/util/constants.ts
> +        'Amount',
done!

2022-09-01 11:11 UTC, ruegenbfr approved these changes

2022-09-01 11:25 UTC, merged