Add github actions to pull requests.
SiLeBAT/fcl-client pull request #794
Opened 2024-08-22 11:07 UTC by arne-z

Add a github action running build, lint, and test jobs that runs automatically on pull requests.

2024-08-22 20:44 UTC, ruegenbfr commented on .github/workflows/build.yml
> +      - run: npm run ng build
Please use `npm run build:qa?` instead.

2024-08-23 07:21 UTC, arne-z commented on .github/workflows/build.yml
> +      - run: npm run ng build
Makes sense.

2024-08-27 09:00 UTC, arne-z commented
Is this cleared to merge now @ruegenbfr?

2024-08-27 13:16 UTC, ruegenbfr requested changes
Please change node version from 18 to 16.

If you like, you can add a job for audit with the command

```
npm run audit -- --level=high --production 
```

2024-08-28 07:42 UTC, merged